const { createTemplateSnapshot, getTemplateById } = require("../../../../config/templates");

const courseVslDeckTemplate = getTemplateById("course-vsl-deck");
const SCRIPT_DRIVEN_DURATION_LABEL = "Determined by script length";

const defaultProjects = [
  {
    id: "yt-tech-news",
    title: "YouTube Tech News",
    goal: "Weekly tech news roundup for YouTube channel. Energetic and fast-paced.",
    type: "Long Form / YouTube",
    status: "Active",
    templateId: null,
    templateSnapshot: null,
    review: {
      scenePlan: { status: "pending", approvedAt: null },
      finalAssembly: { status: "pending", approvedAt: null },
    },
    references: [],
    scriptLinkedReferences: [],
    createdAt: "2026-03-30T08:00:00.000Z",
    updatedAt: "2026-03-30T08:00:00.000Z",
    script: {
      mode: "ai",
      topic: "Weekly tech news roundup",
      content: "Part 1: AI chipmakers are racing to secure the next wave of demand.\nPart 2: New consumer launches are shifting how people compare devices.\nPart 3: Regulation is starting to shape product decisions more directly.\nPart 4: The takeaway is that speed alone no longer guarantees market leadership.",
      model: "gpt",
      source: "generated",
      updatedAt: "2026-03-30T08:05:00.000Z",
    },
    scenes: [],
    audio: {
      narration: {
        voiceId: "elevenlabs-default",
        language: "english",
        status: "draft",
        textPreview: "",
        estimatedDuration: "00:00",
        generatedSource: null,
      },
      music: {
        mode: "auto",
        trackName: "",
        mood: "cinematic",
        generationBrief: "",
        uploadedTracks: [],
        generatedSource: null,
        endingFadeEnabled: true,
        endingFadeDuration: 2.5,
        dynamicVolume: true,
        status: "draft",
      },
      sfx: {
        enabled: true,
        density: "medium",
        status: "draft",
        cues: [],
      },
      generatedAt: null,
    },
    captions: {
      status: "draft",
      generatedAt: null,
      style: {
        captionPosition: "center",
        animationStyle: "pop",
        animationIntensity: 62,
        wordByWord: true,
        wordHighlight: true,
        typography: "bold",
        textSize: 52,
        letterSpacing: 1.5,
        colorStyle: "purple",
        strokeEnabled: false,
        strokeWidth: 0,
        strokeOpacity: 0,
        strokeColor: "black",
        watermarkEnabled: false,
        watermarkText: "",
        watermarkOpacity: 0,
        watermarkPosition: "top-right",
      },
      cues: [],
    },
    settings: {
      scriptAgentModel: "gpt",
      imageAgentModel: "nano-banana",
      videoAgentModel: "kling-3.0",
      voiceId: "elevenlabs-default",
      projectLanguage: "english",
      tone: "energetic, informative, fast-paced",
      visualStyle: "Cyberpunk, neon lighting, highly detailed tech components",
      targetDuration: SCRIPT_DRIVEN_DURATION_LABEL,
      graphics: {
        focusedModuleId: "text-reveal",
        moduleState: {
          "text-reveal": true,
          "lower-third": false,
          "stat-counter": false,
        },
        variantState: {
          "text-reveal": "Viral",
          "lower-third": "Minimal",
          "stat-counter": "Burst",
        },
      },
      effects: {
        clipMode: "video",
        motionStyle: "vertical-pan",
        moduleState: {
          "reactive-fx": true,
          "hook-effect": false,
          "video-ending": true,
        },
        videoEndingDuration: 2,
      },
    },
  },
  {
    id: "tiktok-motivation",
    title: "TikTok Motivation Shorts",
    goal: "Daily motivational quotes with cinematic backgrounds.",
    type: "Short Form / TikTok",
    status: "Completed",
    templateId: null,
    templateSnapshot: null,
    review: {
      scenePlan: { status: "pending", approvedAt: null },
      finalAssembly: { status: "pending", approvedAt: null },
    },
    references: [],
    scriptLinkedReferences: [],
    createdAt: "2026-03-25T08:00:00.000Z",
    updatedAt: "2026-03-25T08:00:00.000Z",
    script: {
      mode: "manual",
      topic: "",
      content: "Success is built one disciplined action at a time. Keep moving, even when the results are not visible yet.",
      model: "gpt",
      source: "manual",
      updatedAt: "2026-03-25T08:00:00.000Z",
    },
    scenes: [],
    audio: {
      narration: {
        voiceId: "elevenlabs-default",
        language: "english",
        status: "draft",
        textPreview: "",
        estimatedDuration: "00:00",
        generatedSource: null,
      },
      music: {
        mode: "auto",
        trackName: "",
        mood: "uplifting",
        generationBrief: "",
        uploadedTracks: [],
        generatedSource: null,
        endingFadeEnabled: true,
        endingFadeDuration: 2.5,
        dynamicVolume: true,
        status: "draft",
      },
      sfx: {
        enabled: true,
        density: "light",
        status: "draft",
        cues: [],
      },
      generatedAt: null,
    },
    captions: {
      status: "draft",
      generatedAt: null,
      style: {
        captionPosition: "center",
        animationStyle: "pop",
        animationIntensity: 62,
        wordByWord: true,
        wordHighlight: true,
        typography: "bold",
        textSize: 52,
        letterSpacing: 1.5,
        colorStyle: "purple",
        strokeEnabled: false,
        strokeWidth: 0,
        strokeOpacity: 0,
        strokeColor: "black",
        watermarkEnabled: false,
        watermarkText: "",
        watermarkOpacity: 0,
        watermarkPosition: "top-right",
      },
      cues: [],
    },
    settings: {
      scriptAgentModel: "gpt",
      imageAgentModel: "kling-3.0",
      videoAgentModel: "seedance-2.0",
      voiceId: "elevenlabs-default",
      projectLanguage: "english",
      tone: "uplifting, punchy, motivational",
      visualStyle: "Bold typography, vertical framing, energetic light leaks",
      targetDuration: SCRIPT_DRIVEN_DURATION_LABEL,
      graphics: {
        focusedModuleId: "text-reveal",
        moduleState: {
          "text-reveal": true,
          "lower-third": false,
          "stat-counter": false,
        },
        variantState: {
          "text-reveal": "Punch",
          "lower-third": "Minimal",
          "stat-counter": "Burst",
        },
      },
      effects: {
        clipMode: "static",
        motionStyle: "zoom-in-out",
        moduleState: {
          "reactive-fx": true,
          "hook-effect": true,
          "video-ending": true,
        },
        videoEndingDuration: 2,
      },
    },
  },
  {
    id: "slideshow-course",
    title: "Course VSL Slideshow",
    goal: "Educational slides for the marketing course landing page.",
    type: "Slideshow / VSL",
    status: "Draft",
    templateId: courseVslDeckTemplate?.id || null,
    templateSnapshot: createTemplateSnapshot(courseVslDeckTemplate),
    review: {
      scenePlan: { status: "pending", approvedAt: null },
      finalAssembly: { status: "pending", approvedAt: null },
    },
    references: [],
    scriptLinkedReferences: [],
    createdAt: "2026-03-18T08:00:00.000Z",
    updatedAt: "2026-03-18T08:00:00.000Z",
    script: {
      mode: "ai",
      topic: "Marketing course opening sequence",
      content: "Part 1: Most creators do not fail because they lack information.\nPart 2: They fail because they do not have a clear system.\nPart 3: This course turns scattered tactics into a repeatable content engine.",
      model: "claude",
      source: "generated",
      updatedAt: "2026-03-18T08:10:00.000Z",
    },
    scenes: [],
    audio: {
      narration: {
        voiceId: "elevenlabs-default",
        language: "english",
        status: "draft",
        textPreview: "",
        estimatedDuration: "00:00",
        generatedSource: null,
      },
      music: {
        mode: "auto",
        trackName: "",
        mood: "editorial",
        generationBrief: "",
        uploadedTracks: [],
        generatedSource: null,
        endingFadeEnabled: true,
        endingFadeDuration: 2.5,
        dynamicVolume: true,
        status: "draft",
      },
      sfx: {
        enabled: false,
        density: "light",
        status: "draft",
        cues: [],
      },
      generatedAt: null,
    },
    captions: {
      status: "draft",
      generatedAt: null,
      style: {
        captionPosition: "center",
        animationStyle: "pop",
        animationIntensity: 62,
        wordByWord: true,
        wordHighlight: true,
        typography: "bold",
        textSize: 52,
        letterSpacing: 1.5,
        colorStyle: "violet",
        strokeEnabled: false,
        strokeWidth: 0,
        strokeOpacity: 0,
        strokeColor: "black",
        watermarkEnabled: false,
        watermarkText: "",
        watermarkOpacity: 0,
        watermarkPosition: "top-right",
      },
      cues: [],
    },
    settings: {
      scriptAgentModel: "claude",
      imageAgentModel: "nano-banana",
      videoAgentModel: "seedance-2.0",
      voiceId: "elevenlabs-default",
      projectLanguage: "english",
      tone: "clear, educational, persuasive",
      visualStyle: "Clean diagrams, premium gradients, modern presentation layout",
      targetDuration: SCRIPT_DRIVEN_DURATION_LABEL,
      graphics: {
        focusedModuleId: "lower-third",
        moduleState: {
          "text-reveal": false,
          "lower-third": true,
          "stat-counter": true,
        },
        variantState: {
          "text-reveal": "Editorial",
          "lower-third": "Anchor",
          "stat-counter": "Board",
        },
      },
      effects: {
        clipMode: "static",
        motionStyle: "horizontal-pan",
        moduleState: {
          "reactive-fx": false,
          "hook-effect": false,
          "video-ending": true,
        },
        videoEndingDuration: 3,
      },
    },
  },
];

module.exports = {
  defaultProjects,
};
